# Generated by Django 3.2.3 on 2021-06-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Description of <django.db.models.fields.CharField>'),
        ),
    ]
