# Generated by Django 3.2.4 on 2021-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210616_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
